### ISSUE TITLE
rename Grouping for several datasets to create unique names

### ISSUE THREAD

**Issue by TWendl** [Open-Systems-Pharmacology/Database-for-observed-data#111]
see also https://github.com/Open-Systems-Pharmacology/Digoxin-Model/issues/12

"Gurley 2008b - Control (Perpetrator Placebo) - Digoxin - PO - 0.25 mg - Serum - agg. (n=18)" appears 3 times in the project snapshot with different observed data ids:
226
228
6162
Belz et al. 1983 - Digoxin control - Digoxin - PO - 0.125 mg - Plasma - agg. (n=12) appears 2 times for the ids
16164
16166
Gurley 2006 - day 1 plasma - Digoxin - PO - 0.4 mg - serum - agg. (n=16) appears 2 times for the ids
16321
16323
Gurley 2007 - control - Digoxin - PO - 0.5 mg - serum - agg. (n=20) appears 2 times for the ids
16325
16327

**Comment by Yuri05** [comment]
fixed with the last PR. closing.

@TWendl in order to automatically close issues with merged PRs - please reference them correctly as described in https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue )
